desirated_framerate: 60
display_shell_interface: true
is_zmq_api_enabled: true
is_serial_enabled: false
color_schemes:
  - - red
    - green
    - blue
  - - red
  - - green
  - - blue
audio_ports:
  - max_frequency: 12000
    min_frequency: 200
    min_volume_threshold: 1.0e-07
    n_rolling_history: 4
    name: Built-in Microphone
    number_of_audio_samples: 24
    sampling_rate: 44000
strips:
  - name: Horizontal Bar
    serial_port_name: /dev/tty.usbserial-A50285BI
    active_state_index: 0
    is_online: false
    midi_ports_for_changing_mode:
      - Audio2Led ChangeMod Bar 1
    midi_ports_for_visualization:
    original_physical_shape:
      - 40
    midi_range:
      - 47
      - 73
    scene:
      shapes:
        - pixel_range:
            - 0
            - 40
          svg_string: M0,0 T300,0
    states:
      - name: Example 1
        active_visualizer_effect: scroll
        active_color_scheme_index: 0
        active_audio_channel_index: 0
        audio_samples_filter_min: 0
        audio_samples_filter_max: 24
        audio_gain: 1
        audio_decay: 0.1
        division_value: 0
        max_brightness: 255
        time_interval: 1
        chunk_size: 7
        blur_value: 0.1
        is_reverse: false
        is_mirror: false
